### ISSUE TITLE
Problems compiling the code

### ISSUE THREAD

**Issue by nimmi15370** [nahueltaibo/fish-feeder#1]
I am delighted with the project, have printed everything and bought the parts according to your list. So far everything is great. However, I'm a total novice when it comes to programming and I can't get any further.

When compiling I get the following error message:

In file included from c:\Users\User\Documents\Arduino\libraries\ESP32_ISR_Servo\src/ESP32_ISR_Servo.hpp:79,
                 from c:\Users\User\Documents\Arduino\libraries\ESP32_ISR_Servo\src/ESP32_ISR_Servo.h:34,
                 from C:\Users\User\Documents\Arduino\sketch_jun16a\sketch_jun16a.ino:9:
c:\Users\User\Documents\Arduino\libraries\ESP32_ISR_Servo\src/ESP32FastTimerInterrupt.hpp: In member function 'bool ESP32TimerInterrupt::setFrequency(const float&, timer_callback)':
c:\Users\User\Documents\Arduino\libraries\ESP32_ISR_Servo\src/ESP32FastTimerInterrupt.hpp:255:23: error: 'TIMER_BASE_CLK' was not declared in this scope
  255 |         _frequency  = TIMER_BASE_CLK / TIMER_DIVIDER;   //1000000;
      |                       ^~~~~~~~~~~~~~
exit status 1

Compilation error: exit status 1

I work with Arduino IDE 2.3.6.
I hope you can help me, otherwise my grandson's fish will starve......

Thank you very much!
